@extends('layouts.admin')

@section('content')
<section class="panel catalog-panel">
    <div class="panel-head"><h2>AI tools</h2><span>{{ $tools->count() }} total</span></div>
    <div class="crud-create"><h3>Add AI tool</h3><p class="form-help">Subdomain mein sirf slug likhein, full URL nahi. Example: <b>ai-speech-to-text</b> se link <b>ai-speech-to-text.faheeminnovations.online</b> banega. Keywords neeche separate field mein likhein.</p><form method="POST" action="{{ route('admin.tools.store') }}" class="crud-form">@csrf
        <div class="tool-fields"><label>Tool name<input name="name" placeholder="Tool name" required></label><label>Subdomain<input name="sub" placeholder="speech-to-text" title="Enter only the slug, not http://localhost or a full URL." required></label><label>Tool link/URL<input type="url" name="url" placeholder="https://example.com/tool"></label></div>
        <div class="tool-fields"><label>Keywords<textarea name="keywords" placeholder="SEO, keyword research, search intent"></textarea></label><label>Short description<textarea name="short" placeholder="Detailed tool description" required></textarea></label><label>Status<select name="status"><option value="live">Live</option><option value="soon">Coming soon</option></select></label></div>
        <button class="primary" type="submit">Add tool</button>
    </form></div>
    <div class="table-scroll"><table><thead><tr><th>Tool</th><th>Subdomain</th><th>Tool link</th><th>Keywords</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    @forelse($tools as $tool)<tr><td><b>{{ $tool->name }}</b><small>{{ $tool->short }}</small></td><td>{{ $tool->sub }}.faheeminnovations.online</td><td>@if($tool->url)<a href="{{ $tool->url }}" target="_blank" rel="noopener">{{ \Illuminate\Support\Str::limit($tool->url, 32) }}</a>@else — @endif</td><td>{{ $tool->keywords ?: '—' }}</td><td><span class="pill {{ $tool->status === 'soon' ? 'new' : '' }}">{{ $tool->status === 'live' ? 'Live' : 'Coming soon' }}</span></td><td class="actions"><details><summary>Edit</summary><form method="POST" action="{{ route('admin.tools.update', $tool) }}" class="edit-form">@csrf @method('PATCH')<label>Tool name<input name="name" value="{{ $tool->name }}" required></label><label>Subdomain<input name="sub" value="{{ $tool->sub }}" title="Spaces become dashes. Use only letters, numbers, dashes, and underscores." required></label><label>Tool link/URL<input type="url" name="url" value="{{ $tool->url }}" placeholder="https://example.com/tool"></label><label>Keywords<textarea name="keywords" placeholder="Keywords, separated by commas">{{ $tool->keywords }}</textarea></label><label>Short description<textarea name="short" required>{{ $tool->short }}</textarea></label><label>Icon<input name="icon" value="{{ $tool->icon }}" required></label><label>Status<select name="status"><option value="live" @selected($tool->status === 'live')>Live</option><option value="soon" @selected($tool->status === 'soon')>Coming soon</option></select></label><button class="primary" type="submit">Save changes</button></form></details><form method="POST" action="{{ route('admin.tools.toggle', $tool) }}">@csrf @method('PATCH')<button class="quiet-link" type="submit">Toggle status</button></form><form method="POST" action="{{ route('admin.tools.destroy', $tool) }}" onsubmit="return confirm('Delete this tool?')">@csrf @method('DELETE')<button class="danger-link" type="submit">Delete</button></form></td></tr>@empty <tr><td colspan="6" class="empty">No tools yet.</td></tr>@endforelse
    </tbody></table></div>
</section>
@endsection
